### ISSUE TITLE
Spotlight Quick Look + Kagi for Safari

### ISSUE THREAD

**Issue by dnisbetjones** [kagisearch/Kagi-Search-for-Safari-macOS#1]
From macOS Ventura onwards, one can now use Quick Look in Spotlight to automatically pull up a search with the space bar. The system uses Safari for this regardless of what the default browser is and as Safari doesn't allow you to set Kagi as a default search engine, it will bypass the Kagi extension on Safari and display whatever is set as default.

![1679252066-514398-image](https://user-images.githubusercontent.com/64179257/226219830-9499c523-7f46-488f-8206-519357133eb3.jpg)

![1679252090-511799-image](https://user-images.githubusercontent.com/64179257/226219825-78193f2e-5bfc-4ae3-b43e-6fdb66ee6a49.jpg)

I don't know if there's a way for the Safari extension to also intercept search queries through Spotlight as it does in the address bar but this would be an excellent feature to implement to really have Kagi as the system-wide default.

**Comment by vprelovac** [comment]
Finding ways around Apple's limitations is really a bad way to spend time and resources. Spotlight should open the default browser when invoked and not Safari. I think sending feedback to Apple would be more efficeint at this point.

**Comment by dnisbetjones** [comment]
That's absolutely fair. I did send feedback to Apple about default search engines in Safari but I will submit additional feedback about Spotlight Quick Look not respecting the default browser.

**Comment by tombuben** [comment]
I'm using firefox and spotlight search opens it as it is my default browser, but defaults to search engine set inside safari. I have the Kagi extension in Firefox, which doesn't do the redirect like the safari extension does though (so the search goes to google if the user didn't set anything in safari).
