### ISSUE TITLE
Inconsistently redirects to Kagi search on Safari 17.0 / macOS Sonoma

### ISSUE THREAD

**Issue by stackptr** [kagisearch/Kagi-Search-for-Safari-macOS#2]
Prior to upgrading to the Sonoma Beta (23A5286g), this extensions redirected searches in Safari from DuckDuckGo to Kagi. After upgrading, this no longer works consistently. There are now three situations I experience:

- Searching in Safari lands on Kagi (i.e., the extension works)
- Searching in Safari lands on DDG with a subsequent refresh landing on Kagi
- Searching in Safari lands on DDG and does not redirect to Kagi after multiple refreshes

Possibly related to the introduction of Profiles, which support using different sets of extensions. Kagi is shown as enabled for both profiles that have been defined in Safari.

**Comment by stackptr** [comment]
Also submitted to KagiFeedback.org: https://kagifeedback.org/d/1708-inconsistently-redirects-to-kagi-search-on-safari-170-macos-sonoma

**Comment by vprelovac** [comment]
This seems to be a Safari/Sonoma bug, nothing to do on our end.
